### ISSUE TITLE
Animation when the target dies

### ISSUE THREAD

**Issue by z2481520838** [LeagueSandbox/GameServer#1312]
When the enemy target is killed, we will not see those relevant animation effects, and these animation will disappear directly in our performance

**Comment by z2481520838** [comment]
It will even affect the animation effect of the attacker

**Comment by lzardy** [comment]
To clarify, this is related to how Death is handled by the removal system (although there is no dedicated removal system, it is sort of everywhere).
When a particle is attached to a dead unit, it is automatically set to be removed the next tick.

**Comment by z2481520838** [comment]
However, the target models that were killed will disappear

**Comment by z2481520838** [comment]
However, the target models that were killed will disappear

**Comment by Killfrra** [comment]
Was fixed by pull request https://github.com/LeagueSandbox/GameServer/pull/1290:
> - Visibility of dead AI no longer changes, they just don't get updates

See also ObjectManager.cs:125

**Comment by cabeca1143** [comment]
> Was fixed by pull request #1290:
> 
> > * Visibility of dead AI no longer changes, they just don't get updates
> 
> See also ObjectManager.cs:125

I think they're still getting removed instantly, there's even an issue with the gold & damage popups sometimes happening on the damage dealer probably due to removal of the minion.
https://youtu.be/x2cCMLugNnA

Minions have a stat `DeathTime` in their file that i'd assume would be a timer for them to be fully removed. Although i'm not so sure because jungle monsters dont have it (mabe they use a default value?).

**Comment by Killfrra** [comment]
Even if they are removed during the next frame on the server, the client does not know about it
